"""
utils/pump_token.py — Secure, signed Pump-ID URL token helper.

Why this exists:
    Plain integer IDs in URLs (e.g. /pump-data/edit/5) allow a user to change
    the number and access any pump record.  This module replaces the raw integer
    with a short, tamper-evident token generated by itsdangerous.URLSafeSerializer.

    The token:
      - Is URL-safe (base64 chars only, no padding issues).
      - Is signed with the application's SECRET_KEY — altering even one character
        causes the decode step to raise itsdangerous.BadSignature, which we treat
        as a 404/403.
      - Does NOT encrypt the payload (the pump ID is still inside), but because it
        is signed the user cannot forge a valid token for a pump they shouldn't
        reach.  For true confidentiality, swap to itsdangerous.URLSafeTimedSerializer
        or add an expiry window.

Usage (in a route):
    from utils.pump_token import encode_pump_id, decode_pump_id

    # Building a URL
    token = encode_pump_id(pump.id)
    url_for('pump_edit', token=token)

    # Resolving a URL token back to the DB primary key
    pump_id = decode_pump_id(token)   # raises BadSignature on tampering → 404
"""

from itsdangerous import URLSafeSerializer, BadSignature

# ---------------------------------------------------------------------------
# Internal salt value.
# Using a salt keeps pump tokens separate from any other serializer usage that
# might share the same SECRET_KEY (e.g. password-reset links).
# ---------------------------------------------------------------------------
_SALT = "pump-id-token-v1"

# Module-level serializer instance; initialised lazily so that this module can
# be imported before the Flask app is created (e.g. in tests).
_serializer: URLSafeSerializer | None = None


def _get_serializer() -> URLSafeSerializer:
    """
    Return the singleton URLSafeSerializer, initialised from the Flask
    application's SECRET_KEY.

    We defer the import of 'current_app' so this module remains importable
    outside a Flask application context (e.g. unit tests that mock the key).
    """
    global _serializer
    if _serializer is None:
        # Import here to avoid a circular dependency at module load time.
        from flask import current_app  # noqa: PLC0415

        # Use the app's secret key — same key that protects sessions.
        # In production, override via the SESSION_SECRET environment variable.
        secret = current_app.config.get("SECRET_KEY") or current_app.secret_key
        _serializer = URLSafeSerializer(secret, salt=_SALT)
    return _serializer


def encode_pump_id(pump_id: int) -> str:
    """
    Convert an integer pump database ID into a signed, URL-safe token string.

    The token is deterministic for a given (secret_key, pump_id) pair, so the
    same pump always produces the same token within a single server deployment.
    Rotating SECRET_KEY automatically invalidates all previously issued tokens.

    Args:
        pump_id: The integer primary-key of the Pump record.

    Returns:
        A short URL-safe string suitable for embedding in a route segment,
        e.g.  "eyJpZCI6NX0.Lz..."
    """
    # Wrap the ID in a small dict so the payload is self-descriptive and
    # less guessable than a bare integer.
    return _get_serializer().dumps({"id": pump_id})


def decode_pump_id(token: str) -> int:
    """
    Validate and unpack a signed token produced by encode_pump_id().

    Args:
        token: The URL token string received from the request path.

    Returns:
        The original integer pump ID.

    Raises:
        itsdangerous.BadSignature: If the token has been tampered with or
            was signed with a different key.  Callers should convert this to
            a 404 or 403 HTTP response.
        KeyError / TypeError: If the token payload is structurally unexpected
            (should never happen with tokens we generated, but handled by
            callers for safety).
    """
    # loads() raises BadSignature automatically if the signature is wrong.
    payload = _get_serializer().loads(token)
    return int(payload["id"])
